name = "iipython-cdbar"
pages_build_output_dir = ".build"
compatibility_date = "2024-09-02"

# Fuck off Cloudflare
send_metrics = false

# Installing manually so I don't need pyproject.toml/package.json
[env.production.vars]
UNSTABLE_PRE_BUILD = "bun i csso-cli uglify-js && rm bun.lockb && pip install beautifulsoup4 minify-html nova-framework"
